---
- name: List Details of Files and Directories
  hosts: all
  become: yes  # This is used to run tasks with elevated privileges

  tasks:
    - name: Create an empty file
      file:
        path: /home/ubuntu/file.txt
        state: touch
   
        
    - name: List details using ls command
      command: ls -l /home/ubuntu
      register: ls_output

    - name: Display ls output
      debug:
        var: ls_output.stdout_lines
        
    - name: List details of files and directories
      find:
        paths: /home/ubuntu
        recurse: yes
      register: file_details

    - name: Display file details
      debug:
        var: file_details.files
