---
- name: Read csv file
  gather_facts: no
  hosts: localhost

  ars:
    csv_file_path: samplecsv.csv

  tasks:
    - name: Read CSV file
      set_fact:
        csv_data: "{{ lookup('csvfile', csv_file_path, delimiter=',') }}"

    - name: Display CSV data
      debug:
        var: csv_data
